<MyLayout>

    canvas.before:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: self.size
            pos: self.pos
    
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height
        padding:50
        spacing:20

        #to place the image
        Image:
            source: 'images/img1.png'
            allow_stretch: True
            keep_ratio: False
        